### PR TITLE
fix(Removing Duplicacy)

### LINKED ISSUE #80: Refactor TabContainer to enhance its usability
Moving conditional checks to TabContainer itself instead of checking it in TopNavigation
1. Remove duplicacy
2. Increase Reusability

### PR DESCRIPTION
**Pull request by shakti97**
Signed-off-by: shakti97 <shaktisingh230797@gmail.com>
Fixes #80 
@DianaLease @dselman have a look and suggest changes if any:)

### CODE REVIEW

File: src/TopNavigation.js [hunk 1]
```diff
@@ -11,15 +11,18 @@ import TemplateList from './TemplateList';
...
 
 function TabContainer(props) {
+    const { value, index } = props;
     return (
-        <Typography component="div" style={{ padding: 8 * 3 }}>
-            {props.children}
-        </Typography>
+        value === index ? <Typography component="div" style={{padding: 8*3}}>
+            {props.children }
+        </Typography> : ''
```
Comment (DianaLease) [inline src/TopNavigation.js]: Can you update to return `null` instead of an empty string on line 18? Otherwise, React will render a text node where we really just don't want to render anything.

**Review by DianaLease — CHANGES_REQUESTED** [review]

**Review by DianaLease — APPROVED** [review]
