### PR TITLE
fix(smart clause dialog): remove state persistence

### LINKED ISSUE #37: Dialog persist state even after closing
New Smart clause dialog preserving the state of the text box

Steps to Reproduce:
1. Go to Create New Smart Clause .
2. Enter Clause Id and Template Id.
3. Close the dialog by clicking on Ok or Cancel
4. Now go to create New Smart Clause Again you will see the text you previously entered.

### PR DESCRIPTION
**Pull request by shakti97**
Signed-off-by: shakti97 <shaktisingh230797@gmail.com>

Fixes #37

### CODE REVIEW

File: src/NewSmartClauseDialog.js [hunk 1]
```diff
@@ -42,17 +42,17 @@ class NewSmartClauseDialog extends Component {
   };
 
   handleCancel = () => {
-    this.setState({ open: false });
+    this.setState({ open: false,clauseId: '', templateId: '' });
```
Comment (DianaLease) [inline src/NewSmartClauseDialog.js]: super small change, but can you add a space before `clauseId` please ?

**Review by DianaLease — CHANGES_REQUESTED** [review]

File: src/NewSmartClauseDialog.js (hunk 1 above)
Comment (shakti97) [reply src/NewSmartClauseDialog.js]: Done

**Comment by shakti97** [comment]
@DianaLease can you please review and suggest changes if any

**Review by DianaLease — APPROVED** [review]
