### PR TITLE
feat(add to contract): fix contract does not add to the current curso…

### LINKED ISSUE #92: clause does not add to the current cursor position of the contract
#### Description
Currently, the `addToContract` function does not add the contract to the current cursor position but rather adds it to the end of the document.

OS config:- Mac OS Catalina (v10.15.2)

### PR DESCRIPTION
**Pull request by nik72619c**
Fixes #92 

Signed-off-by: nik72619c <nikhilsharmarockstar21@gmail.com>

@DianaLease @dselman please review it and let me know of any changes.

### CODE REVIEW

File: src/TemplateEditor/TemplateList.js [hunk 1]
```diff
@@ -81,8 +81,7 @@ const addToContract = async (templateIndex, templateUri) => {
         // console.log(JSON.stringify(dom, null, 2));
         const htmlTransformer = new HtmlTransformer();
         const html = htmlTransformer.toHtml(dom);
-        var blankParagraph = context.document.body.paragraphs.getLast().insertParagraph('', 'After');
-        blankParagraph.insertHtml(html, 'End');
+        context.document.getSelection().insertHtml(html, 'End');
```
Comment (DianaLease) [inline src/TemplateEditor/TemplateList.js]: This is great, but can we instead do
```
context.document.getSelection().insertParagraph('', 'After').insertHtml(html, 'End');
```
so that the clause starts in a new paragraph?

**Review by DianaLease — CHANGES_REQUESTED** [review]

File: src/TemplateEditor/TemplateList.js (hunk 1 above)
Comment (DianaLease) [reply src/TemplateEditor/TemplateList.js]: @nik72619c Following up on the comment above ^

Comment (nik72619c) [reply src/TemplateEditor/TemplateList.js]: got it, making the required changes !

Comment (nik72619c) [reply src/TemplateEditor/TemplateList.js]: @DianaLease made the requested changes :)

**Review by DianaLease — APPROVED** [review]
